apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adservice.yaml
  - cartservice.yaml
  - checkoutservice.yaml
  - currencyservice.yaml
  - emailservice.yaml
  - frontend.yaml
  - loadgenerator.yaml
  - paymentservice.yaml
  - productcatalogservice.yaml
  - recommendationservice.yaml
  - shippingservice.yaml
components:
  - microservices-demo-istio