apiVersion: v2
name: observability
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: kube-prometheus-stack
    version: 62.7.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: opentelemetry-collector
    version: 0.105.1
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: loki
    version: 6.12.0
    repository: https://grafana.github.io/helm-charts
  - name: tempo
    version: 1.10.3
    repository: https://grafana.github.io/helm-charts