kube-prometheus-stack:
  grafana:
    persistence:
      enabled: true
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 50Gi

opentelemetry-collector:
  mode: daemonset
  image:
    repository: otel/opentelemetry-collector-contrib
  presets:
    logsCollection:
      enabled: true
      includeCollectorLogs: true
    kubernetesAttributes:
      enabled: true
      extractAllPodLabels: true
      extractAllPodAnnotations: true
    kubernetesEvents:
      enabled: true
  service:
    enabled: true

  alternateConfig:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
      memory_limiter:
        check_interval: 5s
        spike_limit_mib: 25
        limit_percentage: 80

    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
      pprof:

    exporters:
      debug: { }
      loki:
        endpoint: http://observability-loki-distributed-gateway.monitoring/loki/api/v1/push
      otlphttp/tempo:
        endpoint: http://tempo-gateway.monitoring/otlp
      prometheusremotewrite:
        endpoint: http://observability-kube-prometh-prometheus.monitoring:9090/api/v1/write

    service:
      extensions: [ health_check, pprof ]
      pipelines:
        logs:
          receivers: [ otlp ]
          processors: [ memory_limiter, batch ]
          exporters: [ loki, debug ]
        traces:
          receivers: [ otlp ]
          processors: [ memory_limiter, batch ]
          exporters: [ debug ]
        metrics:
          receivers: [ otlp ]
          processors: [ memory_limiter, batch ]
          exporters: [ prometheusremotewrite, debug ]