apiVersion: v2
name: rca-env
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: grafana
    alias: grafana
    condition: grafana.enabled
    repository: https://grafana.github.io/helm-charts
    version: 8.5.1
  - name: loki-distributed
    alias: loki
    condition: loki.enabled
    repository: https://grafana.github.io/helm-charts
    version: 0.79.3
  - name: mimir-distributed
    alias: mimir
    condition: mimir.enabled
    repository: https://grafana.github.io/helm-charts
    version: 5.5.0-weekly.308
  - name: tempo-distributed
    alias: tempo
    condition: tempo.enabled
    repository: https://grafana.github.io/helm-charts
    version: 1.18.0
  - name: oncall
    alias: grafana-oncall
    condition: grafana-oncall.enabled
    repository: https://grafana.github.io/helm-charts
    version: 1.9.25
  - name: k8s-monitoring
    alias: k8s-monitoring
    condition: k8s-monitoring.enabled
    repository: https://grafana.github.io/helm-charts
    version: 1.5.1